import Images from "./Images";

export const meals = [
  {
    name: "Fitness",
    image: Images.Fitness,
    color: "#25854d",
  },
  {
    name: "Bulking",
    image: Images.Bulking,
    color: "#e90f08",
  },
  {
    name: "Fatloss",
    image: Images.Fatloss,
    color: "#faac04",
  },
  {
    name: "Lean Muscle",
    image: Images.LeanMuscle,
    color: "#25854d",
  },
  {
    name: "Carbs",
    image: Images.Carbs,
    color: "#e90f08",
  },
  {
    name: "Protein",
    image: Images.Protein,
    color: "#faac04",
  },
];

export const sports = [
  {
    name: "Sprint/Jogg",
    image: Images.Sprint,
  },
  {
    name: "Cycling",
    image: Images.Cycling,
  },
  {
    name: "Swimming",
    image: Images.Swimming,
  },
  {
    name: "Weightlifting",
    image: Images.Weightlifts,
  },
  {
    name: "Pilates",
    image: Images.Pilates,
  },
  {
    name: "Basketball",
    image: Images.Basketball,
  },
  {
    name: "Football",
    image: Images.Football,
  },
  {
    name: "Tennis",
    image: Images.Tennis,
  },
  {
    name: "Boxing",
    image: Images.Boxing,
  },
  {
    name: "CrossFit",
    image: Images.Crossfit,
  },
];

export const banners = [
  {
    name: "banner1",
    image: Images.Banner1,
    primaryText: "BIG OFFER!",
    primarySubText: "Get 20% Off On All Foods",
    secondaryText: "Offer Expires On 31st December",
  },
  {
    name: "banner2",
    image: Images.Banner2,
    primaryText: "BIG OFFER!",
    primarySubText: "Get 20% Off On All Foods",
    secondaryText: "Offer Expires On 31st December",
  },
  {
    name: "banner3",
    image: Images.Banner3,
    primaryText: "BIG OFFER!",
    primarySubText: "Get 20% Off On All Foods",
    secondaryText: "Offer Expires On 31st December",
  },
  {
    name: "banner4",
    image: Images.Banner4,
    primaryText: "BIG OFFER!",
    primarySubText: "Get 20% Off On All Foods",
    secondaryText: "Offer Expires On 31st December",
  }
];

export const cartItems = [
  {
    id: '1',
    name: 'Beef Pizza',
    price: 12.00,
    quantity: 1,
    image: require("../../../assets/foods25.jpg"), // Replace with actual image URL
  },
  {
    id: '2',
    name: 'Egg Burger',
    price: 11.00,
    quantity: 2,
    image: require("../../../assets/foods26.jpg"), // Replace with actual image URL
  },
  {
    id: '3',
    name: 'Cucumber Salad Salad Salad',
    price: 12.00,
    quantity: 2,
    image: require("../../../assets/foods27.jpg"), // Replace with actual image URL
  },
  {
    id: '4',
    name: 'Cucumber Salad',
    price: 12.00,
    quantity: 2,
    image: require("../../../assets/foods27.jpg"), // Replace with actual image URL
  },
  {
    id: '5',
    name: 'Cucumber Salad',
    price: 12.00,
    quantity: 2,
    image: require("../../../assets/foods27.jpg"), // Replace with actual image URL
  },
  {
    id: '6',
    name: 'Cucumber Salad',
    price: 12.00,
    quantity: 2,
    image: require("../../../assets/foods27.jpg"), // Replace with actual image URL
  },
];

export const menuItems = [
  {
    id: "1",
    name: "Spicy Noodles",
    subTitle: "A fiery delight",
    description: "Delicious noodles tossed with fresh vegetables and a spicy sauce that will tantalize your taste buds.",
    price: "500",
    image: require("../../../assets/foods15.jpg"),
    rating: 4.5,
    nutrients: {
      carbs: "70g",
      proteins: "10g",
      fats: "20g",
      sugar: "5g",
    },
    kcal: "348",
    ingredients: [
      { name: "Noodles" },
      { name: "Vegetables" },
      { name: "Spicy Sauce" },
    ],
    category: "Carbs",
    mealType: "Lunch",
  },
  {
    id: "2",
    name: "Shrimp Pasta",
    subTitle: "Seafood sensation",
    description: "Succulent shrimp combined with al dente pasta and a rich, creamy sauce.",
    price: "800",
    image: require("../../../assets/foods16.jpg"),
    rating: 4.7,
    nutrients: {
      carbs: "60g",
      proteins: "25g",
      fats: "15g",
      sugar: "6g",
    },
    kcal: "348",
    ingredients: [
      { name: "Shrimp" },
      { name: "Pasta" },
      { name: "Creamy Sauce" },
    ],
    category: "Protein",
    mealType: "Dinner",
  },
  {
    id: "3",
    name: "Vegetable Curry",
    subTitle: "Healthy and hearty",
    description: "A variety of fresh vegetables simmered in a fragrant, spicy curry sauce.",
    price: "200",
    image: require("../../../assets/foods19.jpg"),
    rating: 4.3,
    nutrients: {
      carbs: "45g",
      proteins: "7g",
      fats: "10g",
      sugar: "8g",
    },
    kcal: "348",
    ingredients: [
      { name: "Vegetables" },
      { name: "Curry Sauce" },
      { name: "Spices" },
    ],
    category: "Fitness",
    mealType: "Lunch",
  },
  {
    id: "4",
    name: "Mixed Salad",
    subTitle: "Fresh and crisp",
    description: "A refreshing blend of crisp greens, juicy tomatoes, cucumbers, and a light vinaigrette.",
    price: "500",
    image: require("../../../assets/foods20.jpg"),
    rating: 4.0,
    nutrients: {
      carbs: "20g",
      proteins: "5g",
      fats: "8g",
      sugar: "4g",
    },
    kcal: "348",
    ingredients: [
      { name: "Greens" },
      { name: "Tomatoes" },
      { name: "Cucumbers" },
    ],
    category: "Fitness",
    mealType: "Lunch",
  },
  {
    id: "5",
    name: "Chicken Pasta Salad",
    subTitle: "Perfect for lunch",
    description: "Grilled chicken and pasta combined with fresh vegetables and a tangy dressing.",
    price: "500",
    image: require("../../../assets/foods25.jpg"),
    rating: 4.6,
    nutrients: {
      carbs: "50g",
      proteins: "30g",
      fats: "15g",
      sugar: "7g",
    },
    kcal: "348",
    ingredients: [
      { name: "Chicken" },
      { name: "Pasta" },
      { name: "Vegetables" },
    ],
    category: "Protein",
    mealType: "Lunch",
  },
  {
    id: "6",
    name: "Beef Salad",
    subTitle: "Savory and satisfying",
    description: "Tender beef slices served on a bed of fresh greens with a flavorful dressing.",
    price: "200",
    image: require("../../../assets/foods26.jpg"),
    rating: 4.2,
    nutrients: {
      carbs: "15g",
      proteins: "25g",
      fats: "18g",
      sugar: "2g",
    },
    kcal: "348",
    ingredients: [
      { name: "Beef" },
      { name: "Greens" },
      { name: "Dressing" },
    ],
    category: "Protein",
    mealType: "Dinner",
  },
  {
    id: "7",
    name: "Margarita Pizza",
    subTitle: "Classic Italian",
    description: "Traditional pizza with fresh tomatoes, mozzarella cheese, and basil leaves.",
    price: "600",
    image: require("../../../assets/foods27.jpg"),
    rating: 4.8,
    nutrients: {
      carbs: "60g",
      proteins: "20g",
      fats: "22g",
      sugar: "5g",
    },
    kcal: "348",
    ingredients: [
      { name: "Tomatoes" },
      { name: "Mozzarella" },
      { name: "Basil" },
    ],
    category: "Carbs",
    mealType: "Dinner",
  },
  {
    id: "8",
    name: "Grilled Salmon",
    subTitle: "Healthy and delicious",
    description: "Perfectly grilled salmon fillet served with a side of steamed vegetables.",
    price: "1200",
    image: require("../../../assets/foods28.jpg"),
    rating: 4.9,
    nutrients: {
      carbs: "5g",
      proteins: "35g",
      fats: "20g",
      sugar: "2g",
    },
    kcal: "348",
    ingredients: [
      { name: "Salmon" },
      { name: "Vegetables" },
      { name: "Spices" },
    ],
    category: "Protein",
    mealType: "Dinner",
  },
  {
    id: "9",
    name: "Cheeseburger",
    subTitle: "American favorite",
    description: "Juicy beef patty topped with melted cheese, lettuce, tomato, and onion.",
    price: "700",
    image: require("../../../assets/foods29.jpg"),
    rating: 4.5,
    nutrients: {
      carbs: "45g",
      proteins: "25g",
      fats: "30g",
      sugar: "7g",
    },
    kcal: "348",
    ingredients: [
      { name: "Beef Patty" },
      { name: "Cheese" },
      { name: "Lettuce" },
    ],
    category: "Bulking",
    mealType: "Lunch",
  },
  {
    id: "10",
    name: "Chicken Wings",
    subTitle: "Finger-licking good",
    description: "Crispy chicken wings coated in a spicy buffalo sauce, served with ranch dressing.",
    price: "400",
    image: require("../../../assets/foods31.jpg"),
    rating: 4.4,
    nutrients: {
      carbs: "10g",
      proteins: "20g",
      fats: "25g",
      sugar: "3g",
    },
    kcal: "348",
    ingredients: [
      { name: "Chicken Wings" },
      { name: "Buffalo Sauce" },
      { name: "Ranch Dressing" },
    ],
    category: "Bulking",
    mealType: "Snack",
  },
  {
    id: "11",
    name: "Tacos",
    subTitle: "Mexican street food",
    description: "Soft tortillas filled with seasoned beef, fresh salsa, and guacamole.",
    price: "300",
    image: require("../../../assets/foods8.jpg"),
    rating: 4.6,
    nutrients: {
      carbs: "30g",
      proteins: "15g",
      fats: "12g",
      sugar: "4g",
    },
    kcal: "348",
    ingredients: [
      { name: "Tortillas" },
      { name: "Seasoned Beef" },
      { name: "Salsa" },
    ],
    category: "Protein",
    mealType: "Lunch",
  },
  {
    id: "12",
    name: "Sushi Platter",
    subTitle: "Japanese delicacy",
    description: "Assorted sushi rolls with fresh fish, avocado, and cucumber.",
    price: "1500",
    image: require("../../../assets/foods7.jpg"),
    rating: 4.8,
    nutrients: {
      carbs: "55g",
      proteins: "30g",
      fats: "10g",
      sugar: "5g",
    },
    kcal: "348",
    ingredients: [
      { name: "Fish" },
      { name: "Avocado" },
      { name: "Cucumber" },
    ],
    category: "Protein",
    mealType: "Lunch",
  },
  {
    id: "13",
    name: "Falafel Wrap",
    subTitle: "Middle Eastern delight",
    description: "Crispy falafel balls wrapped in pita bread with hummus and fresh vegetables.",
    price: "350",
    image: require("../../../assets/foods6.jpg"),
    rating: 4.3,
    nutrients: {
      carbs: "40g",
      proteins: "12g",
      fats: "18g",
      sugar: "3g",
    },
    kcal: "348",
    ingredients: [
      { name: "Falafel" },
      { name: "Pita Bread" },
      { name: "Hummus" },
    ],
    category: "Fitness",
    mealType: "Lunch",
  },
  {
    id: "14",
    name: "Pancakes",
    subTitle: "Breakfast favorite",
    description: "Fluffy pancakes served with maple syrup and fresh berries.",
    price: "250",
    image: require("../../../assets/foods5.jpg"),
    rating: 4.7,
    nutrients: {
      carbs: "70g",
      proteins: "8g",
      fats: "20g",
      sugar: "12g",
    },
    kcal: "348",
    ingredients: [
      { name: "Pancakes" },
      { name: "Maple Syrup" },
      { name: "Berries" },
    ],
    category: "Carbs",
    mealType: "Breakfast",
  },
  {
    id: "15",
    name: "Chocolate Cake",
    subTitle: "Decadent dessert",
    description: "Rich and moist chocolate cake topped with creamy chocolate frosting.",
    price: "450",
    image: require("../../../assets/foods4.jpg"),
    rating: 4.9,
    nutrients: {
      carbs: "60g",
      proteins: "5g",
      fats: "25g",
      sugar: "35g",
    },
    kcal: "348",
    ingredients: [
      { name: "Chocolate Cake" },
      { name: "Chocolate Frosting" },
      { name: "Cream" },
    ],
    category: "Fatloss",
    mealType: "Desert",
  },
];

